version: "3.1"
services:
  database:
    image: library/postgres:13.1
    container_name: mybatis-sample-postgres
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: mybatis_sample
      POSTGRES_USER: mybatis_sample
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --auth-local=md5 --auth-host=md5"
      TZ: "Asia/Tokyo"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
